// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCN3qFUW8H2xPV-paEhVFm5zQoRTxgZOc4',
    appId: '1:122044429576:web:bcf8b5b2c5cf3e644f28bd',
    messagingSenderId: '122044429576',
    projectId: 'prover-fitness',
    authDomain: 'prover-fitness.firebaseapp.com',
    storageBucket: 'prover-fitness.firebasestorage.app',
    measurementId: 'G-32M75NWE9L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiVXr-xJwmCPOWsNdOxeGtJGOVuzhK7w4',
    appId: '1:122044429576:android:3ae50a924da0181b4f28bd',
    messagingSenderId: '122044429576',
    projectId: 'prover-fitness',
    storageBucket: 'prover-fitness.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMbYjtjapXdva9J1IM9z6-XQscY9pView',
    appId: '1:122044429576:ios:8a26db7a4f40d8944f28bd',
    messagingSenderId: '122044429576',
    projectId: 'prover-fitness',
    storageBucket: 'prover-fitness.firebasestorage.app',
    iosBundleId: 'com.example.fitnessApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMbYjtjapXdva9J1IM9z6-XQscY9pView',
    appId: '1:122044429576:ios:8a26db7a4f40d8944f28bd',
    messagingSenderId: '122044429576',
    projectId: 'prover-fitness',
    storageBucket: 'prover-fitness.firebasestorage.app',
    iosBundleId: 'com.example.fitnessApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCN3qFUW8H2xPV-paEhVFm5zQoRTxgZOc4',
    appId: '1:122044429576:web:2980359effd24c4e4f28bd',
    messagingSenderId: '122044429576',
    projectId: 'prover-fitness',
    authDomain: 'prover-fitness.firebaseapp.com',
    storageBucket: 'prover-fitness.firebasestorage.app',
    measurementId: 'G-QGB2BSDS5K',
  );
}
